config/routes.rb
Rails.application.routes.draw do

  
  
  
  

  
#home section  
  root  'static_pages#home'	
  get 'intro' => 'static_pages#intro'

  #ap seminar

  get 'seminar_home' => 'ap_seminars#seminar_home'
  get 'lesson_1' => 'ap_seminars#seminar_lesson_1'
  get 'lesson_2' => 'ap_seminars#seminar_lesson_2'


  #ap history
  get 'history_home' => 'ap_history#history_home'
  get 'history_lesson_1' => 'ap_history#lesson_1'
  get 'history_lesson_2' => 'ap_history#lesson_2'

  #ap research

  get 'research_home' => 'research#research_home'
  get 'research_lesson_1' => 'research#lesson_1'
  get 'research_lesson_2' => 'ap_research#lesson_2'


  #ap English
  
  get 'english_home' => 'english#home'
  get 'english_lesson_1' => 'english#lesson_1'
  get 'english_lesson_2' => 'english#lesson_2'
 
  

  
#   # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/ap_history_controller.rb
class ApHistoryController < ApplicationController

	layout "history_layout"
	
  def history_home
  end

  def lesson_1
  end

  def lesson_2
  end
end

app/controllers/ap_research_controller.rb
class ApResearchController < ApplicationController


	layout "research_layout"

  def research_home
  end

  def lesson_1
  end

  def lesson_2
  end
end

app/controllers/ap_seminars_controller.rb
class ApSeminarsController < ApplicationController

	 layout "seminar_layout"

  def seminar_home
  end

  def seminar_lesson_1
  end

  def seminar_lesson_2
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/english_controller.rb
class EnglishController < ApplicationController

	layout 'english_layout'
	
  def home
  end

  def lesson_1
  end

  def lesson_2
  end
end

app/controllers/research_controller.rb
class ResearchController < ApplicationController

	layout "research_layout"
	
  def research_home
  end

  def lesson_1
  end

  def lesson_2
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def intro
  end
end

app/helpers/ap_english_helper.rb
module ApEnglishHelper
end

app/helpers/ap_history_helper.rb
module ApHistoryHelper
end

app/helpers/ap_research_helper.rb
module ApResearchHelper
end

app/helpers/ap_seminars_helper.rb
module ApSeminarsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

	def full_title(page_title = ' ')
		base_title = "South Shore Studies"
		if page_title.empty?
			base_title
		else
			page_title + " | " + base_title
		end
	end
end

app/helpers/english_helper.rb
module EnglishHelper
end

app/helpers/research_helper.rb
module ResearchHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper

	def full_title(page_title = ' ')
		base_title = "South Shore Studies"
		if page_title.empty?
			base_title
		else
			page_title + " | " + base_title
		end
	end
end

app/views/ap_history/history_home.html.erb
<h1>ApHistory#history_home</h1>
<p>Find me in app/views/ap_history/history_home.html.erb</p>

app/views/ap_history/lesson_1.html.erb
<h1>ApHistory#lesson_1</h1>
<p>Find me in app/views/ap_history/lesson_1.html.erb</p>

app/views/ap_history/lesson_2.html.erb
<h1>ApHistory#lesson_2</h1>
<p>Find me in app/views/ap_history/lesson_2.html.erb</p>

app/views/ap_research/lesson_1.html.erb
<h1>ApResearch#lesson_1</h1>
<p>Find me in app/views/ap_research/lesson_1.html.erb</p>

app/views/ap_research/lesson_2.html.erb
<h1>ApResearch#lesson_2</h1>
<p>Find me in app/views/ap_research/lesson_2.html.erb</p>

app/views/ap_research/research_home.html.erb
<h1>ApResearch#research_home</h1>
<p>Find me in app/views/ap_research/research_home.html.erb</p>

app/views/ap_seminars/seminar_home.html.erb
<h1>Ap Seminar</h1>

app/views/ap_seminars/seminar_lesson_1.html.erb
<h1>Lesson 1</h1>

app/views/ap_seminars/seminar_lesson_2.html.erb
<% provide(:title, "AP Seminar") %>



<h1>Lesson 2</h1> 

app/views/english/home.html.erb
<h1>English#home</h1>
<p>Find me in app/views/english/home.html.erb</p>

app/views/english/lesson_1.html.erb
<h1>English#lesson_1</h1>
<p>Find me in app/views/english/lesson_1.html.erb</p>

app/views/english/lesson_2.html.erb
<h1>English#lesson_2</h1>
<p>Find me in app/views/english/lesson_2.html.erb</p>

app/views/layouts/_english_head.html.erb
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css">

<nav class="navbar navbar-inverse navbar-static-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "AP English",   english_home_path %></li>
        <li><%= link_to "Lesson 1",   english_lesson_1_path %></li>
        <li><%= link_to "Lesson 2",   english_lesson_2_path %>/li>
        
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_header.html.erb
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css">

<nav class="navbar navbar-inverse navbar-static-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "AP Seminar",    seminar_home_path %></li>
        <!-- <li><%= link_to "Intro",   intro_path %></li>
        <li><%= link_to "AP History",   history_home_path %></li>
        <li><%= link_to "AP Research",   research_home_path %></li>
        <li><%= link_to "AP English",   english_home_path %></li> -->
        <li><%= link_to "Log in", '#' %></li>
      </ul>
    </div>
  </div>
</nav>
    



    


   

app/views/layouts/_history_head.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "SSS", root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home",   history_home_path %></li>
            <li><%= link_to "Lesson 1",   history_lesson_1_path %></li>
            <li><%= link_to "Lesson 2",   history_lesson_2_path %></li>
            
          </ul>
        </nav>
      </div>
    </header>

app/views/layouts/_research_head.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "SSS", root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">

            <li><%= link_to "Home", research_home_path %></li>
            <li><%= link_to "Lesson 1",  research_lesson_1_path %></li>
            <li><%= link_to "Lesson 2",  research_lesson_2_path %></li>

          
         
          </ul>
        </nav>
      </div>

    </header>




    </header>

app/views/layouts/_seminar_head.html.erb
 <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "SSS", root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home",   seminar_home_path %></li>
            <li><%= link_to "Lesson 1",   lesson_1_path %></li>
            <li><%= link_to "Lesson 2",   lesson_2_path %></li>
            
          </ul>
        </nav>
      </div>
    </header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/_under_construction.html.erb
<div class = "center jumbotron">
	
	<%= image_tag("sss.png", width: 300) %>



<h3>Under Construction</h3>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
   <%= javascript_pack_tag 'application' %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
   
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>
 

app/views/layouts/english_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
   <%= javascript_pack_tag 'application' %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/english_head' %>
   
    <div class="container">
      <%= yield %>

      <%= render 'layouts/under_construction' %>
    </div>
  </body>
</html>

app/views/layouts/history_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
   <%= javascript_pack_tag 'application' %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/history_head' %>
   
    <div class="container">

      
      <%= yield %>

      <%= render 'layouts/under_construction' %>
    </div>
  </body>
</html>

app/views/layouts/research_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
   <%= javascript_pack_tag 'application' %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
<!-- <<<<<<< HEAD -->
<!-- <<<<<<< HEAD -->
    <!-- <%= render 'layouts/history_head' %>
======= -->
    <%= render 'layouts/research_head' %>
<!-- >>>>>>> 74f21996e13f02fefcdb3fc8635072396ee28d5a
=======
    <%= render 'layouts/research_head' %>
>>>>>>> added and connected research menu and layout again again
    -->
    <div class="container">
      <%= yield %>

      <%= render 'layouts/under_construction' %>
    </div>
  </body>
</html>

app/views/layouts/seminar_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
   <%= javascript_pack_tag 'application' %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/seminar_head' %>
   
    <div class="container">
      <%= yield %>

      <%= render 'layouts/under_construction' %>
    </div>
  </body>
</html>

app/views/research/lesson_1.html.erb
<h1>Research#lesson_1</h1>
<p>Find me in app/views/research/lesson_1.html.erb</p>

app/views/research/lesson_2.html.erb
<h1>Research#lesson_2</h1>
<p>Find me in app/views/research/lesson_2.html.erb</p>

app/views/research/research_home.html.erb
<h1>Research#research_home</h1>
<p>Find me in app/views/research/research_home.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>


<title><%= yield(:title) %> | South Shore Studies </title>

<div class="center jumbotron">

	<%= image_tag("sss.png", width: 200) %>
	<h1>South Shore Studies</h1>


<h3>AP Seminar, AP Research, AP History, & AP English Tutoring</h3>

<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>


<%= link_to "Sign up now!", '#' , class: "btn btn lg btn-primary" %>



</div>

app/views/static_pages/intro.html.erb
<% provide(:title, "Intro") %>

<title><%= yield(:title) %> | South Shore Studies </title>




<h1>StaticPages#intro</h1>